services:
  bangumi-api:
    build: .
    container_name: bangumi-data-api
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CACHE_TTL=${CACHE_TTL:-3600}
      - REQUIRE_API_KEY=${REQUIRE_API_KEY:-false}
      - API_KEYS=${API_KEYS:-}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT:-8000}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s